### ISSUE TITLE
Component for labels and values in forms

### ISSUE THREAD

**Issue by bigboypantson** [brandymedia/turbine-ui-core#2]
Just building some forms and forgive me if this already exists, I could do with the ability to build my edit form with all the text inputs and then have some key => value data in the form using the same spacings etc as inputs but it would just allow me to embed whatever content I want.

So I have:

First Name -> input
Last Name -> input

Email Verified At -> I may want to push in some html with a button to resend verify email etc and keep existing spacing

Another Field -> input

Does this make sense? am I missing something?

**Comment by brandymedia** [comment]
There is not a specific component that retains the same spacing as input fields as such, although you can achieve this with some of the existing components and a small bit of custom Tailwind.

```
<form action="">
    <x-t-input
        type="text"
        name="first_name"
        label="First Name"
    />
    <x-t-input
        type="text"
        name="last_name"
        label="Last Name"
    />
    <x-t-label>
        Email Verified At
    </x-t-label>
    <x-t-card
        class="mb-5"
    >
        <x-slot:body>
            <x-t-grid cols="2" gap class="items-center">
                <x-t-text
                    size="sm"
                    class="mb-0"
                >
                    14-12-2023
                </x-t-text>
                <div class="flex md:justify-end">
                    <x-t-button
                        variant="success"
                        size="sm"
                    >
                        Resend verify email
                    </x-t-button>
                </div>
            </x-t-grid>
        </x-slot:body>
    </x-t-card>
    <x-t-input
        type="text"
        name="another_field"
        label="Another Field"
    />
</form>
```
